apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k6-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: k6
  endpoints:
    - port: metrics
      interval: 30s