name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy-cluster:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout this Github repository
      uses: actions/checkout@v4
    - name: Login to Microsoft Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Cache Terraform Plugin Dir
      uses: actions/cache@v3
      with:
        path: ~/.terraform.d/plugin-cache
        key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
        restore-keys: |
          terraform-plugin-cache-${{ runner.os }}-
    - name: Destroy DOKS Terraform Resources
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      run: |
        set -e

        echo "Initializing and validating Terraform configuration"
        terraform init
        terraform validate

        cat <<EOF > terraform.tfvars.json
        {
          "do_token": "${{ secrets.DO_API_TOKEN }}",  
          "cloudflare_api_token": "${{ secrets.CLOUDFLARE_TOKEN }}",
          "cloudflare_zone_id": "${{ secrets.CLOUDFLARE_ZONE_ID }}",
          "datadog_api_key": "${{ secrets.DATADOG_API_KEY }}",
          "datadog_app_key": "${{ secrets.DATADOG_APP_KEY }}"
        }
        EOF

        echo "Configuring Terraform to use plugin cache"
        mkdir -p ~/.terraform.d/plugin-cache
        echo 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

        echo "Attempting to destroy Terraform Resources (max 3 attempts)..."
        for destroy in {1..3}; do
          echo "Attempt $destroy..."
          terraform destroy --auto-approve && break || {
            echo "Terraform destroy failed (attempt $destroy)."
            if [ "$destroy" -lt 3 ]; then
              echo "Retrying in 10 seconds..."
              sleep 10
            else
              echo "All attempts failed..."
              exit 1
            fi
          }
        done
      working-directory: ./terraform
    - name: Commit Terraform Lock File
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update terraform.lock.hcl"
        file_pattern: "terraform/.terraform.lock.hcl"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
